Repository AGH-Narzedzia-Informatyczne-2023-2024/what2watch, pull requests merged in 2023-11, with the labels that each got.

#9 zebranie danych
  interfejs.py
Labels: enhancement

#10 pytaniado_user.py
  lunchbranch.py
Labels: Improvement

#8 plik z kodem z pythona na rng
  README.md
  rng.py
Labels: In review, Improvement

#12 dodanie pliku z listą
  bazafilmow.txt
Labels: enhancement

#13 instrukcja pobrania aplikacji mobilnej
  jak_pobrac.txt
Labels: good first issue, help wanted, Improvement
